buildVariable: false
familyName: Noto Sans Limbu
googleFonts: true
includeSubsets:
- from: Noto Sans
  name: GF_Latin_Core
- from: Noto Sans Devanagari
  ranges:
  - end: 2405
    start: 2404
recipeProvider: noto
sources:
- NotoSansLimbu.glyphs
